language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "6"

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11

sudo: false
